/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospitalmanagement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class prescription extends javax.swing.JFrame {

    /**
     * Creates new form prescription
     */String Pname ;
     String Pid;
    public prescription(String Pname, String Pid) {
        initComponents();
        loaditems();
           this.Pname= Pname;
           this.Pid = Pid;
        lb2Id.setText(Pid);
        lbName.setText(Pname);
    }
    
    public String getPname(){
        return Pname;
    }
    public String getPid(){
        return Pid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb2Id = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        tfDuration = new javax.swing.JTextField();
        tfDosage = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tfDrug = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prescription");
        jLabel1.setOpaque(true);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Dosage");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 210, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Patient Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 60, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Patient ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 110, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Drug Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 160, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Duration");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 260, 120, 30);
        jPanel1.add(lb2Id);
        lb2Id.setBounds(380, 110, 110, 30);
        jPanel1.add(lbName);
        lbName.setBounds(380, 60, 110, 30);

        tfDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDurationActionPerformed(evt);
            }
        });
        jPanel1.add(tfDuration);
        tfDuration.setBounds(380, 260, 130, 30);
        jPanel1.add(tfDosage);
        tfDosage.setBounds(380, 210, 130, 30);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 350, 140, 40);

        jPanel1.add(tfDrug);
        tfDrug.setBounds(380, 150, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background1.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 680, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDurationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String PName =  getPname();
        String Pid = getPid();
       
        String DrugName = (String)tfDrug.getSelectedItem();
        String Dosage = tfDosage.getText();
         String Duration  = tfDuration.getText();
         System.out.println("inside precription value of Pid AND pNAME"+Pid+"  "+PName);
         
        if( PName.equals("")|| Pid.equals("")|| DrugName.equals("")||Dosage.equals("")||Duration.equals("")){
         JOptionPane.showMessageDialog(this, "All feild are Required!!!!");
        }
       else {
        
         
        try {
            
             ResultSet rs = DBLoader.executeQuery("select * from prescription ");

            rs.moveToInsertRow();
            
            rs.updateString("PatientId", Pid);
            rs.updateString("PatientName", PName);
            rs.updateString("DrugName", DrugName);
            rs.updateString("Dosage", Dosage);
           // rs.updateDate("Date", Duration);
            rs.updateString("Duration", Duration);
            rs.insertRow();
            
            JOptionPane.showMessageDialog(rootPane, "Prescription Add successfully!!!!!!!!");
                
            
            tfDosage.setText(" ");
           tfDrug.setSelectedItem(" ");
           tfDuration.setText(" ");
            
          
            
            
        } catch (SQLException ex) {
            Logger.getLogger(PatientRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
     public void loaditems(){
         
        try {
             ResultSet rs = DBLoader.executeQuery("select * from items ");
            while(rs.next()){
                tfDrug.addItem(rs.getString("ItemsName"));
            }
             
            
        } catch (SQLException ex) {
            Logger.getLogger(appointments.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb2Id;
    private javax.swing.JLabel lbName;
    private javax.swing.JTextField tfDosage;
    private javax.swing.JComboBox<String> tfDrug;
    private javax.swing.JTextField tfDuration;
    // End of variables declaration//GEN-END:variables
}
